export const PAISES = [
  "Brasil",
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Arábia Saudita",
  "Argélia",
  "Argentina",
  "Armênia",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Bélgica",
  "Belize",
  "Benin",
  "Bielorrússia",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Butão",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Cingapura",
  "Colômbia",
  "Congo",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eslováquia",
  "Eslovênia",
  "Espanha",
  "Estados Unidos",
  "Estônia",
  "Etiópia",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gana",
  "Geórgia",
  "Grécia",
  "Guatemala",
  "Guiana",
  "Guiné",
  "Guiné-Bissau",
  "Haiti",
  "Honduras",
  "Hungria",
  "Iêmen",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jordânia",
  "Kuwait",
  "Laos",
  "Letônia",
  "Líbano",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Macedônia do Norte",
  "Madagascar",
  "Malásia",
  "Malawi",
  "Mali",
  "Malta",
  "Marrocos",
  "Maurício",
  "Mauritânia",
  "México",
  "Moçambique",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Namíbia",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Noruega",
  "Nova Zelândia",
  "Omã",
  "Países Baixos",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polônia",
  "Portugal",
  "Quênia",
  "Quirguistão",
  "Reino Unido",
  "República Dominicana",
  "República Tcheca",
  "Romênia",
  "Ruanda",
  "Rússia",
  "Senegal",
  "Sérvia",
  "Síria",
  "Somália",
  "Sri Lanka",
  "Sudão",
  "Suécia",
  "Suíça",
  "Suriname",
  "Tailândia",
  "Taiwan",
  "Tanzânia",
  "Timor-Leste",
  "Togo",
  "Trinidad e Tobago",
  "Tunísia",
  "Turquia",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Venezuela",
  "Vietnã",
  "Zâmbia",
  "Zimbábue",
  "Outro",
] as const;

export const UFS = [
  "AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO",
] as const;
