/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as CheckoutFormRouteImport } from './routes/checkout-form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutRetornoRouteImport } from './routes/checkout/retorno'
import { Route as AdminUploadGuiaRouteImport } from './routes/admin/upload-guia'
import { Route as AdminPainelRouteImport } from './routes/admin/painel'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicPagamentosSigilopayRouteImport } from './routes/api/public/pagamentos/sigilopay'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFormRoute = CheckoutFormRouteImport.update({
  id: '/checkout-form',
  path: '/checkout-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRetornoRoute = CheckoutRetornoRouteImport.update({
  id: '/checkout/retorno',
  path: '/checkout/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadGuiaRoute = AdminUploadGuiaRouteImport.update({
  id: '/admin/upload-guia',
  path: '/admin/upload-guia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPainelRoute = AdminPainelRouteImport.update({
  id: '/admin/painel',
  path: '/admin/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPagamentosSigilopayRoute =
  ApiPublicPagamentosSigilopayRouteImport.update({
    id: '/api/public/pagamentos/sigilopay',
    path: '/api/public/pagamentos/sigilopay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout-form': typeof CheckoutFormRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/upload-guia': typeof AdminUploadGuiaRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/public/pagamentos/sigilopay': typeof ApiPublicPagamentosSigilopayRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout-form': typeof CheckoutFormRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/upload-guia': typeof AdminUploadGuiaRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/checkout': typeof CheckoutIndexRoute
  '/api/public/pagamentos/sigilopay': typeof ApiPublicPagamentosSigilopayRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout-form': typeof CheckoutFormRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/upload-guia': typeof AdminUploadGuiaRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/public/pagamentos/sigilopay': typeof ApiPublicPagamentosSigilopayRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout-form'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/admin/painel'
    | '/admin/upload-guia'
    | '/checkout/retorno'
    | '/checkout/'
    | '/api/public/pagamentos/sigilopay'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout-form'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/admin/painel'
    | '/admin/upload-guia'
    | '/checkout/retorno'
    | '/checkout'
    | '/api/public/pagamentos/sigilopay'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/checkout-form'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/admin/painel'
    | '/admin/upload-guia'
    | '/checkout/retorno'
    | '/checkout/'
    | '/api/public/pagamentos/sigilopay'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutFormRoute: typeof CheckoutFormRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AdminPainelRoute: typeof AdminPainelRoute
  AdminUploadGuiaRoute: typeof AdminUploadGuiaRoute
  CheckoutRetornoRoute: typeof CheckoutRetornoRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ApiPublicPagamentosSigilopayRoute: typeof ApiPublicPagamentosSigilopayRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-form': {
      id: '/checkout-form'
      path: '/checkout-form'
      fullPath: '/checkout-form'
      preLoaderRoute: typeof CheckoutFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/retorno': {
      id: '/checkout/retorno'
      path: '/checkout/retorno'
      fullPath: '/checkout/retorno'
      preLoaderRoute: typeof CheckoutRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload-guia': {
      id: '/admin/upload-guia'
      path: '/admin/upload-guia'
      fullPath: '/admin/upload-guia'
      preLoaderRoute: typeof AdminUploadGuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/painel': {
      id: '/admin/painel'
      path: '/admin/painel'
      fullPath: '/admin/painel'
      preLoaderRoute: typeof AdminPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagamentos/sigilopay': {
      id: '/api/public/pagamentos/sigilopay'
      path: '/api/public/pagamentos/sigilopay'
      fullPath: '/api/public/pagamentos/sigilopay'
      preLoaderRoute: typeof ApiPublicPagamentosSigilopayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutFormRoute: CheckoutFormRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AdminPainelRoute: AdminPainelRoute,
  AdminUploadGuiaRoute: AdminUploadGuiaRoute,
  CheckoutRetornoRoute: CheckoutRetornoRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ApiPublicPagamentosSigilopayRoute: ApiPublicPagamentosSigilopayRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
